export const books = [
  {
    id: 1,
    title: 'Donate A Book',
    author: 'DONALD WILLIAM',
    normalPrice: 700.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-1_grande.jpg?v=1613036885',
  },
  {
    id: 2,
    title: 'Endless Summer',
    author: 'JOHN ERIK',
    normalPrice: 800.0,
    salePrice: 300.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-100_grande.jpg?v=1587115881',
  },
  {
    id: 3,
    title: 'Home Made Meals',
    author: 'ALICE JAMES',
    normalPrice: 300.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-34_grande.jpg?v=1587116925',
  },
  {
    id: 4,
    title: 'Home Made Meals',
    author: 'ALICE JAMES',
    normalPrice: 300.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-40_grande.jpg?v=1587119146',
  },
  {
    id: 5,
    title: 'Home Made Meals',
    author: 'ALICE JAMES',
    normalPrice: 300.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-44_grande.jpg?v=1587117561',
  },
  {
    id: 6,
    title: 'Home Made Meals',
    author: 'ALICE JAMES',
    normalPrice: 300.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-65_grande.jpg?v=1587118346',
  },
  {
    id: 7,
    title: 'Home Made Meals',
    author: 'ALICE JAMES',
    normalPrice: 300.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-46_grande.jpg?v=1587118513',
  },
  {
    id: 8,
    title: 'Home Made Meals',
    author: 'ALICE JAMES',
    normalPrice: 300.0,
    salePrice: 120.0,
    imageUrl:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-4_grande.jpg?v=1587113962',
  },
];

export const blogs = [
  {
    id: 0,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-1.jpg?v=1585546169',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 1,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-2.jpg?v=1585546218',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 2,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-3.jpg?v=1585546251',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 3,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-7.JPG?v=1585981240',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 4,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-6.JPG?v=1585981209',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 5,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-10.JPG?v=1585981370',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 6,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-9.JPG?v=1585981316',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 7,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-11.JPG?v=1585981380',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
  {
    id: 8,
    imageUrl: 'https://cdn.shopify.com/s/files/1/0359/5979/9852/articles/blog-8.JPG?v=1585981274',
    subTitle: 'Ramamoorthi M',
    title: 'Books changed my ideology',
    text: 'The standard Lorem Ipsum passage, used since the 1500s &quot;Lorem ipsum...',
  },
];

export const countries = [
  { id: 0, code: 'VN', value: 'Vietnam' },
  { id: 1, code: 'XK', value: 'Kosovo' },
  { id: 2, code: 'NG', value: 'Nigeria' },
  { id: 3, code: 'ID', value: 'Indonesia' },
  { id: 4, code: 'AF', value: 'Afghanistan' },
  { id: 5, code: 'AX', value: 'Islands' },
  { id: 6, code: 'AL', value: 'Albania' },
  { id: 7, code: 'DZ', value: 'Algeria' },
  { id: 8, code: 'AD', value: 'Andorra' },
  { id: 9, code: 'AO', value: 'Angola' },
  { id: 10, code: 'AI', value: 'Anguilla' },
  { id: 11, code: 'AG', value: 'Barbuda' },
  { id: 12, code: 'AR', value: 'Argentina' },
  { id: 13, code: 'AM', value: 'Armenia' },
  { id: 14, code: 'AW', value: 'Aruba' },
  { id: 15, code: 'AC', value: 'Island' },
  { id: 16, code: 'AU', value: 'Australia' },
  { id: 17, code: 'AT', value: 'Austria' },
  { id: 18, code: 'AZ', value: 'Azerbaijan' },
  { id: 19, code: 'BS', value: 'Bahamas' },
  { id: 20, code: 'BH', value: 'Bahrain' },
  { id: 21, code: 'BD', value: 'Bangladesh' },
  { id: 22, code: 'BB', value: 'Barbados' },
  { id: 23, code: 'BY', value: 'Belarus' },
  { id: 24, code: 'BE', value: 'Belgium' },
  { id: 25, code: 'BZ', value: 'Belize' },
  { id: 26, code: 'BJ', value: 'Benin' },
  { id: 27, code: 'BM', value: 'Bermuda' },
  { id: 28, code: 'BT', value: 'Bhutan' },
  { id: 29, code: 'BO', value: 'Bolivia' },
  { id: 30, code: 'BA', value: 'Herzegovina' },
  { id: 31, code: 'BW', value: 'Botswana' },
  { id: 32, code: 'BV', value: 'Island' },
  { id: 33, code: 'BR', value: 'Brazil' },
  { id: 34, code: 'IO', value: 'Territory' },
  { id: 35, code: 'VG', value: 'British' },
  { id: 36, code: 'BN', value: 'Brunei' },
  { id: 37, code: 'BG', value: 'Bulgaria' },
  { id: 38, code: 'BF', value: 'Faso' },
  { id: 39, code: 'BI', value: 'Burundi' },
  { id: 40, code: 'KH', value: 'Cambodia' },
  { id: 41, code: 'CM', value: 'Cameroon' },
  { id: 42, code: 'CA', value: 'Canada' },
  { id: 43, code: 'CV', value: 'Verde' },
  { id: 44, code: 'BQ', value: 'Netherlands' },
  { id: 45, code: 'KY', value: 'Islands' },
  { id: 46, code: 'CF', value: 'Republic' },
  { id: 47, code: 'TD', value: 'Chad' },
  { id: 48, code: 'CL', value: 'Chile' },
  { id: 49, code: 'CN', value: 'China' },
  { id: 50, code: 'CX', value: 'Island' },
  { id: 51, code: 'CC', value: 'Islands' },
  { id: 52, code: 'CO', value: 'Colombia' },
  { id: 53, code: 'KM', value: 'Comoros' },
  { id: 54, code: 'CG', value: 'Congo' },
  { id: 55, code: 'CD', value: 'The' },
  { id: 56, code: 'CK', value: 'Islands' },
  { id: 57, code: 'CR', value: 'Rica' },
  { id: 58, code: 'HR', value: 'Croatia' },
  { id: 59, code: 'CW', value: 'Curaçao' },
  { id: 60, code: 'CY', value: 'Cyprus' },
  { id: 61, code: 'CZ', value: 'Republic' },
  { id: 62, code: 'CI', value: 'dIvoire' },
  { id: 63, code: 'DK', value: 'Denmark' },
  { id: 64, code: 'DJ', value: 'Djibouti' },
  { id: 65, code: 'DM', value: 'Dominica' },
  { id: 66, code: 'DO', value: 'Republic' },
  { id: 67, code: 'EC', value: 'Ecuador' },
  { id: 68, code: 'EG', value: 'Egypt' },
  { id: 69, code: 'SV', value: 'Salvador' },
  { id: 70, code: 'GQ', value: 'Guinea' },
  { id: 71, code: 'ER', value: 'Eritrea' },
  { id: 72, code: 'EE', value: 'Estonia' },
  { id: 73, code: 'SZ', value: 'Eswatini' },
  { id: 74, code: 'ET', value: 'Ethiopia' },
  { id: 75, code: 'FK', value: 'Malvinas)' },
  { id: 76, code: 'FO', value: 'Islands' },
  { id: 77, code: 'FJ', value: 'Fiji' },
  { id: 78, code: 'FI', value: 'Finland' },
  { id: 79, code: 'FR', value: 'France' },
  { id: 80, code: 'GF', value: 'Guiana' },
  { id: 81, code: 'PF', value: 'Polynesia' },
  { id: 82, code: 'TF', value: 'Territories' },
  { id: 83, code: 'GA', value: 'Gabon' },
  { id: 84, code: 'GM', value: 'Gambia' },
  { id: 85, code: 'GE', value: 'Georgia' },
  { id: 86, code: 'DE', value: 'Germany' },
  { id: 87, code: 'GH', value: 'Ghana' },
  { id: 88, code: 'GI', value: 'Gibraltar' },
  { id: 89, code: 'GR', value: 'Greece' },
  { id: 90, code: 'GL', value: 'Greenland' },
  { id: 91, code: 'GD', value: 'Grenada' },
  { id: 92, code: 'GP', value: 'Guadeloupe' },
  { id: 93, code: 'GT', value: 'Guatemala' },
  { id: 94, code: 'GG', value: 'Guernsey' },
  { id: 95, code: 'GN', value: 'Guinea' },
  { id: 96, code: 'GW', value: 'Bissau' },
  { id: 97, code: 'GY', value: 'Guyana' },
  { id: 98, code: 'HT', value: 'Haiti' },
  { id: 99, code: 'HM', value: 'Islands' },
  { id: 100, code: 'HN', value: 'Honduras' },
  { id: 101, code: 'HK', value: 'Kong' },
  { id: 102, code: 'HU', value: 'Hungary' },
  { id: 103, code: 'IS', value: 'Iceland' },
  { id: 104, code: 'IN', value: 'India' },
  { id: 105, code: 'ID', value: 'Indonesia' },
  { id: 106, code: 'IQ', value: 'Iraq' },
  { id: 107, code: 'IE', value: 'Ireland' },
  { id: 108, code: 'IM', value: 'Man' },
  { id: 109, code: 'IL', value: 'Israel' },
  { id: 110, code: 'IT', value: 'Italy' },
  { id: 111, code: 'JM', value: 'Jamaica' },
  { id: 112, code: 'JP', value: 'Japan' },
  { id: 113, code: 'JE', value: 'Jersey' },
  { id: 114, code: 'JO', value: 'Jordan' },
  { id: 115, code: 'KZ', value: 'Kazakhstan' },
  { id: 116, code: 'KE', value: 'Kenya' },
  { id: 117, code: 'KI', value: 'Kiribati' },
  { id: 118, code: 'XK', value: 'Kosovo' },
  { id: 119, code: 'KW', value: 'Kuwait' },
  { id: 120, code: 'KG', value: 'Kyrgyzstan' },
  { id: 121, code: 'LA', value: 'Republic' },
  { id: 122, code: 'LV', value: 'Latvia' },
  { id: 123, code: 'LB', value: 'Lebanon' },
  { id: 124, code: 'LS', value: 'Lesotho' },
  { id: 125, code: 'LR', value: 'Liberia' },
  { id: 126, code: 'LY', value: 'Jamahiriya' },
  { id: 127, code: 'LI', value: 'Liechtenstein' },
  { id: 128, code: 'LT', value: 'Lithuania' },
  { id: 129, code: 'LU', value: 'Luxembourg' },
  { id: 130, code: 'MO', value: 'Macao' },
  { id: 131, code: 'MG', value: 'Madagascar' },
  { id: 132, code: 'MW', value: 'Malawi' },
  { id: 133, code: 'MY', value: 'Malaysia' },
  { id: 134, code: 'MV', value: 'Maldives' },
  { id: 135, code: 'ML', value: 'Mali' },
  { id: 136, code: 'MT', value: 'Malta' },
  { id: 137, code: 'MQ', value: 'Martinique' },
  { id: 138, code: 'MR', value: 'Mauritania' },
  { id: 139, code: 'MU', value: 'Mauritius' },
  { id: 140, code: 'YT', value: 'Mayotte' },
  { id: 141, code: 'MX', value: 'Mexico' },
  { id: 142, code: 'MD', value: 'of' },
  { id: 143, code: 'MC', value: 'Monaco' },
  { id: 144, code: 'MN', value: 'Mongolia' },
  { id: 145, code: 'ME', value: 'Montenegro' },
  { id: 146, code: 'MS', value: 'Montserrat' },
  { id: 147, code: 'MA', value: 'Morocco' },
  { id: 148, code: 'MZ', value: 'Mozambique' },
  { id: 149, code: 'MM', value: 'Myanmar' },
  { id: 150, code: 'NA', value: 'Namibia' },
  { id: 151, code: 'NR', value: 'Nauru' },
  { id: 152, code: 'NP', value: 'Nepal' },
  { id: 153, code: 'NL', value: 'Netherlands' },
  { id: 154, code: 'NC', value: 'Caledonia' },
  { id: 155, code: 'NZ', value: 'Zealand' },
  { id: 156, code: 'NI', value: 'Nicaragua' },
  { id: 157, code: 'NE', value: 'Niger' },
  { id: 158, code: 'NG', value: 'Nigeria' },
  { id: 159, code: 'NU', value: 'Niue' },
  { id: 160, code: 'NF', value: 'Island' },
  { id: 161, code: 'MK', value: 'Macedonia' },
  { id: 162, code: 'NO', value: 'Norway' },
  { id: 163, code: 'OM', value: 'Oman' },
  { id: 164, code: 'PK', value: 'Pakistan' },
  { id: 165, code: 'PS', value: 'Occupied' },
  { id: 166, code: 'PA', value: 'Panama' },
  { id: 167, code: 'PG', value: 'Guinea' },
  { id: 168, code: 'PY', value: 'Paraguay' },
  { id: 169, code: 'PE', value: 'Peru' },
  { id: 170, code: 'PH', value: 'Philippines' },
  { id: 171, code: 'PN', value: 'Pitcairn' },
  { id: 172, code: 'PL', value: 'Poland' },
  { id: 173, code: 'PT', value: 'Portugal' },
  { id: 174, code: 'QA', value: 'Qatar' },
  { id: 175, code: 'RE', value: 'Reunion' },
  { id: 176, code: 'RO', value: 'Romania' },
  { id: 177, code: 'RU', value: 'Russia' },
  { id: 178, code: 'RW', value: 'Rwanda' },
  { id: 179, code: 'WS', value: 'Samoa' },
  { id: 180, code: 'SM', value: 'Marino' },
  { id: 181, code: 'ST', value: 'Principe' },
  { id: 182, code: 'SA', value: 'Arabia' },
  { id: 183, code: 'SN', value: 'Senegal' },
  { id: 184, code: 'RS', value: 'Serbia' },
  { id: 185, code: 'SC', value: 'Seychelles' },
  { id: 186, code: 'SL', value: 'Leone' },
  { id: 187, code: 'SG', value: 'Singapore' },
  { id: 188, code: 'SX', value: 'Maarten' },
  { id: 189, code: 'SK', value: 'Slovakia' },
  { id: 190, code: 'SI', value: 'Slovenia' },
  { id: 191, code: 'SB', value: 'Islands' },
  { id: 192, code: 'SO', value: 'Somalia' },
  { id: 193, code: 'ZA', value: 'Africa' },
  { id: 194, code: 'GS', value: 'Islands' },
  { id: 195, code: 'KR', value: 'Korea' },
  { id: 196, code: 'SS', value: 'Sudan' },
  { id: 197, code: 'ES', value: 'Spain' },
  { id: 198, code: 'LK', value: 'Lanka' },
  { id: 199, code: 'BL', value: 'Barthélemy' },
  { id: 200, code: 'SH', value: 'Helena' },
  { id: 201, code: 'KN', value: 'Nevis' },
  { id: 202, code: 'LC', value: 'Lucia' },
  { id: 203, code: 'MF', value: 'Martin' },
  { id: 204, code: 'PM', value: 'Miquelon' },
  { id: 205, code: 'VC', value: 'Vincent' },
  { id: 206, code: 'SD', value: 'Sudan' },
  { id: 207, code: 'SR', value: 'Suriname' },
  { id: 208, code: 'SJ', value: 'Mayen' },
  { id: 209, code: 'SE', value: 'Sweden' },
  { id: 210, code: 'CH', value: 'Switzerland' },
  { id: 211, code: 'TW', value: 'Taiwan' },
  { id: 212, code: 'TJ', value: 'Tajikistan' },
  { id: 213, code: 'TZ', value: 'Of' },
  { id: 214, code: 'TH', value: 'Thailand' },
  { id: 215, code: 'TL', value: 'Leste' },
  { id: 216, code: 'TG', value: 'Togo' },
  { id: 217, code: 'TK', value: 'Tokelau' },
  { id: 218, code: 'TO', value: 'Tonga' },
  { id: 219, code: 'TT', value: 'Tobago' },
  { id: 220, code: 'TA', value: 'Cunha' },
  { id: 221, code: 'TN', value: 'Tunisia' },
  { id: 222, code: 'TR', value: 'Turkey' },
  { id: 223, code: 'TM', value: 'Turkmenistan' },
  { id: 224, code: 'TC', value: 'Islands' },
  { id: 225, code: 'TV', value: 'Tuvalu' },
  { id: 226, code: 'UM', value: 'Islands' },
  { id: 227, code: 'UG', value: 'Uganda' },
  { id: 228, code: 'UA', value: 'Ukraine' },
  { id: 229, code: 'AE', value: 'Emirates' },
  { id: 230, code: 'GB', value: 'Kingdom' },
  { id: 231, code: 'US', value: 'States' },
  { id: 232, code: 'UY', value: 'Uruguay' },
  { id: 233, code: 'UZ', value: 'Uzbekistan' },
  { id: 234, code: 'VU', value: 'Vanuatu' },
  { id: 235, code: 'VA', value: 'State)' },
  { id: 236, code: 'VE', value: 'Venezuela' },
  { id: 237, code: 'VN', value: 'Vietnam' },
  { id: 238, code: 'WF', value: 'Futuna' },
  { id: 239, code: 'EH', value: 'Sahara' },
  { id: 240, code: 'YE', value: 'Yemen' },
  { id: 241, code: 'ZM', value: 'Zambia' },
  { id: 242, code: 'ZW', value: 'Zimbabwe' },
];

export const productCart = [
  {
    id: 0,
    img:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-76_small.jpg?v=1587116682',
    title: 'Girls at the Golden City',
    type: 'Audible Audiobook',
    language: 'Hebrew',
    price: 300,
    quantity: 1,
  },
  {
    id: 1,
    img:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/booknew-3_small.jpg?v=1587119671',
    title: 'When The Stars Align',
    type: 'Kindle Edition',
    language: 'Japanese',
    price: 300,
    quantity: 1,
  },
  {
    id: 2,
    img:
      'https://cdn.shopify.com/s/files/1/0359/5979/9852/products/shop-new-87_small.jpg?v=1587118936',
    title: 'The Stadium by Night',
    type: 'Hardcover',
    language: 'Spanish',
    price: 320,
    quantity: 1,
  },
];
