export const CREATE_EMPTY_CART = 'CREATE_EMPTY_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const UPDATE_QUANTITY = 'UPDATE_QUANTITY';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_NOTE = 'UPDATE_CART_NOTE';
